package at.ac.tuwien.sepm.groupphase.backend.endpoint.mapper;

import at.ac.tuwien.sepm.groupphase.backend.endpoint.dto.NotificationDto;
import at.ac.tuwien.sepm.groupphase.backend.entity.Notification;
import at.ac.tuwien.sepm.groupphase.backend.service.UserService;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * A mapper, whose implementation is generated by Mapstruct
 * (see <a href="https://mapstruct.org/">https://mapstruct.org/</a>),
 * that handles conversions between a {@link Notification notification entity} and related DTOs.
 */
@Mapper(componentModel = "spring", uses = {UserService.class})
public abstract class NotificationMapper {

    @Mapping(source = "user.id", target = "userId")
    public abstract NotificationDto notificationToNotificationDto(Notification notification);

    @Mapping(source = "userId", target = "user")
    public abstract Notification notificationDtoToNotification(NotificationDto notificationDto);
}
