package at.ac.tuwien.sepm.groupphase.backend.utils.enums;

public enum NotificationType {
    COMMISSION_CANDIDATE_ADDED,
    COMMISSION_CANDIDATE_REMOVED,
    COMMISSION_SKETCH_ADDED,
    COMMISSION_FEEDBACK_ADDED,
    COMMISSION_STATUS_CANCELLED,
    COMMISSION_STATUS_IN_PROGRESS,
    COMMISSION_STATUS_COMPLETED,
    COMMISSION_STATUS_NEGOTIATING,
    COMMISSION_CANDIDATE_CHOSEN,
    COMMISSION_REVIEW_ADDED,
    COMMISSION_PAID_FOR,
    REPORT_OFFENSIVE_IMAGES,
    REPORT_STRONG_LANGUAGE,
    REPORT_RACIST_REMARKS,
    REPORT_ILLEGAL_ART,
    REPORT_STOLEN_ART
}